import pytest
from sort_packages import sort

##Most of this code was generated by Cursor Agent mode (using gpt4.1)
def test_standard_package():
    # Not bulky, not heavy
    assert sort(10, 10, 10, 5) == "STANDARD"

def test_bulky_package():
    # Bulky due to volume
    assert sort(100, 100, 101, 5) == "SPECIAL"
    # Bulky due to dimension
    assert sort(151, 10, 10, 5) == "SPECIAL"
    assert sort(10, 151, 10, 5) == "SPECIAL"
    assert sort(10, 10, 151, 5) == "SPECIAL"

def test_heavy_package():
    # Heavy but not bulky
    assert sort(10, 10, 10, 25) == "SPECIAL"

def test_rejected_package():
    # Both heavy and bulky
    assert sort(200, 200, 200, 25) == "REJECTED"
    # Both heavy and bulky (dimension)
    assert sort(151, 10, 10, 25) == "REJECTED"
    assert sort(10, 151, 10, 25) == "REJECTED"
    assert sort(10, 10, 151, 25) == "REJECTED"

def test_type_error():
    with pytest.raises(TypeError):
        sort('a', 10, 10, 5)
    with pytest.raises(TypeError):
        sort(10, 'b', 10, 5)
    with pytest.raises(TypeError):
        sort(10, 10, 'c', 5)
    with pytest.raises(TypeError):
        sort(10, 10, 10, 'd')

def test_value_error():
    with pytest.raises(ValueError):
        sort(0, 10, 10, 5)
    with pytest.raises(ValueError):
        sort(10, 0, 10, 5)
    with pytest.raises(ValueError):
        sort(10, 10, 0, 5)
    with pytest.raises(ValueError):
        sort(10, 10, 10, 0)
    with pytest.raises(ValueError):
        sort(-1, 10, 10, 5)
    with pytest.raises(ValueError):
        sort(10, -1, 10, 5)
    with pytest.raises(ValueError):
        sort(10, 10, -1, 5)
    with pytest.raises(ValueError):
        sort(10, 10, 10, -1)

